apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/openeye0/argo-cd-example.git
    targetRevision: HEAD
    path: manifests/helm-guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true